<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251031105159 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6680DC1166D1F9C ON project_image (project_id)');
        $this->addSql('ALTER TABLE project_image ADD CONSTRAINT FK_D6680DC1166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT fk_4c62e6382a68f4d1');
        $this->addSql('DROP INDEX idx_4c62e6382a68f4d1');
        $this->addSql('ALTER TABLE contact ADD firstname VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE contact ADD lastname VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE contact ADD phone TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE contact DROP formule_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_image DROP CONSTRAINT FK_D6680DC1166D1F9C');
        $this->addSql('DROP TABLE project_image');
        $this->addSql('ALTER TABLE contact ADD formule_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contact DROP firstname');
        $this->addSql('ALTER TABLE contact DROP lastname');
        $this->addSql('ALTER TABLE contact DROP phone');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT fk_4c62e6382a68f4d1 FOREIGN KEY (formule_id) REFERENCES formule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_4c62e6382a68f4d1 ON contact (formule_id)');
    }
}
