<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250523180350 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE contact ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE contact ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE formule ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE formule ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE project ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE project ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tags ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tags ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE project ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE project ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE formule ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE formule ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE contact ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE contact ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tags ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tags ALTER id DROP IDENTITY
        SQL);
    }
}
